// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openbeacon.proto

public final class Openbeacon {
  private Openbeacon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ObUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    OB_UNIT_NONE(0, 0),
    OB_UNIT_PIXEL(1, 1),
    OB_UNIT_MILLIMETER(2, 2),
    OB_UNIT_CENTIMETER(3, 3),
    OB_UNIT_METER(4, 4),
    OB_UNIT_INCH(5, 5),
    OB_UNIT_FEET(6, 6),
    OB_UNIT_YARD(7, 7),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static ObUnit valueOf(int value) {
      switch (value) {
        case 0: return OB_UNIT_NONE;
        case 1: return OB_UNIT_PIXEL;
        case 2: return OB_UNIT_MILLIMETER;
        case 3: return OB_UNIT_CENTIMETER;
        case 4: return OB_UNIT_METER;
        case 5: return OB_UNIT_INCH;
        case 6: return OB_UNIT_FEET;
        case 7: return OB_UNIT_YARD;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ObUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ObUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ObUnit>() {
            public ObUnit findValueByNumber(int number) {
              return ObUnit.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Openbeacon.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ObUnit[] VALUES = {
      OB_UNIT_NONE, OB_UNIT_PIXEL, OB_UNIT_MILLIMETER, OB_UNIT_CENTIMETER, OB_UNIT_METER, OB_UNIT_INCH, OB_UNIT_FEET, OB_UNIT_YARD, 
    };
    public static ObUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private ObUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      Openbeacon.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:ObUnit)
  }
  
  public static final class ObTracking extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ObTracking> {
    // Use ObTracking.newBuilder() to construct.
    private ObTracking() {
      initFields();
    }
    private ObTracking(boolean noInit) {}
    
    private static final ObTracking defaultInstance;
    public static ObTracking getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObTracking getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openbeacon.internal_static_ObTracking_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openbeacon.internal_static_ObTracking_fieldAccessorTable;
    }
    
    // optional sint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private boolean hasX;
    private int x_ = 0;
    public boolean hasX() { return hasX; }
    public int getX() { return x_; }
    
    // optional sint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private boolean hasY;
    private int y_ = 0;
    public boolean hasY() { return hasY; }
    public int getY() { return y_; }
    
    // optional sint32 z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private boolean hasZ;
    private int z_ = 0;
    public boolean hasZ() { return hasZ; }
    public int getZ() { return z_; }
    
    // optional .ObUnit unit = 4;
    public static final int UNIT_FIELD_NUMBER = 4;
    private boolean hasUnit;
    private Openbeacon.ObUnit unit_;
    public boolean hasUnit() { return hasUnit; }
    public Openbeacon.ObUnit getUnit() { return unit_; }
    
    // repeated uint32 reader_id = 5;
    public static final int READER_ID_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> readerId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getReaderIdList() {
      return readerId_;
    }
    public int getReaderIdCount() { return readerId_.size(); }
    public int getReaderId(int index) {
      return readerId_.get(index);
    }
    
    // optional uint32 tx_strength = 6;
    public static final int TX_STRENGTH_FIELD_NUMBER = 6;
    private boolean hasTxStrength;
    private int txStrength_ = 0;
    public boolean hasTxStrength() { return hasTxStrength; }
    public int getTxStrength() { return txStrength_; }
    
    // optional uint32 area_id = 7;
    public static final int AREA_ID_FIELD_NUMBER = 7;
    private boolean hasAreaId;
    private int areaId_ = 0;
    public boolean hasAreaId() { return hasAreaId; }
    public int getAreaId() { return areaId_; }
    
    // optional uint32 room_id = 8;
    public static final int ROOM_ID_FIELD_NUMBER = 8;
    private boolean hasRoomId;
    private int roomId_ = 0;
    public boolean hasRoomId() { return hasRoomId; }
    public int getRoomId() { return roomId_; }
    
    // optional uint32 building_id = 9;
    public static final int BUILDING_ID_FIELD_NUMBER = 9;
    private boolean hasBuildingId;
    private int buildingId_ = 0;
    public boolean hasBuildingId() { return hasBuildingId; }
    public int getBuildingId() { return buildingId_; }
    
    // optional uint32 installation_id = 10;
    public static final int INSTALLATION_ID_FIELD_NUMBER = 10;
    private boolean hasInstallationId;
    private int installationId_ = 0;
    public boolean hasInstallationId() { return hasInstallationId; }
    public int getInstallationId() { return installationId_; }
    
    private void initFields() {
      unit_ = Openbeacon.ObUnit.OB_UNIT_NONE;
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasX()) {
        output.writeSInt32(1, getX());
      }
      if (hasY()) {
        output.writeSInt32(2, getY());
      }
      if (hasZ()) {
        output.writeSInt32(3, getZ());
      }
      if (hasUnit()) {
        output.writeEnum(4, getUnit().getNumber());
      }
      for (int element : getReaderIdList()) {
        output.writeUInt32(5, element);
      }
      if (hasTxStrength()) {
        output.writeUInt32(6, getTxStrength());
      }
      if (hasAreaId()) {
        output.writeUInt32(7, getAreaId());
      }
      if (hasRoomId()) {
        output.writeUInt32(8, getRoomId());
      }
      if (hasBuildingId()) {
        output.writeUInt32(9, getBuildingId());
      }
      if (hasInstallationId()) {
        output.writeUInt32(10, getInstallationId());
      }
      extensionWriter.writeUntil(128, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, getX());
      }
      if (hasY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, getY());
      }
      if (hasZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, getZ());
      }
      if (hasUnit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, getUnit().getNumber());
      }
      {
        int dataSize = 0;
        for (int element : getReaderIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getReaderIdList().size();
      }
      if (hasTxStrength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getTxStrength());
      }
      if (hasAreaId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, getAreaId());
      }
      if (hasRoomId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, getRoomId());
      }
      if (hasBuildingId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, getBuildingId());
      }
      if (hasInstallationId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, getInstallationId());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Openbeacon.ObTracking parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTracking parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObTracking parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObTracking parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObTracking parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Openbeacon.ObTracking prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Openbeacon.ObTracking, Builder> {
      private Openbeacon.ObTracking result;
      
      // Construct using Openbeacon.ObTracking.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Openbeacon.ObTracking();
        return builder;
      }
      
      protected Openbeacon.ObTracking internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Openbeacon.ObTracking();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openbeacon.ObTracking.getDescriptor();
      }
      
      public Openbeacon.ObTracking getDefaultInstanceForType() {
        return Openbeacon.ObTracking.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Openbeacon.ObTracking build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Openbeacon.ObTracking buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Openbeacon.ObTracking buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.readerId_ != java.util.Collections.EMPTY_LIST) {
          result.readerId_ =
            java.util.Collections.unmodifiableList(result.readerId_);
        }
        Openbeacon.ObTracking returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openbeacon.ObTracking) {
          return mergeFrom((Openbeacon.ObTracking)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Openbeacon.ObTracking other) {
        if (other == Openbeacon.ObTracking.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasUnit()) {
          setUnit(other.getUnit());
        }
        if (!other.readerId_.isEmpty()) {
          if (result.readerId_.isEmpty()) {
            result.readerId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.readerId_.addAll(other.readerId_);
        }
        if (other.hasTxStrength()) {
          setTxStrength(other.getTxStrength());
        }
        if (other.hasAreaId()) {
          setAreaId(other.getAreaId());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasBuildingId()) {
          setBuildingId(other.getBuildingId());
        }
        if (other.hasInstallationId()) {
          setInstallationId(other.getInstallationId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setX(input.readSInt32());
              break;
            }
            case 16: {
              setY(input.readSInt32());
              break;
            }
            case 24: {
              setZ(input.readSInt32());
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              Openbeacon.ObUnit value = Openbeacon.ObUnit.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                setUnit(value);
              }
              break;
            }
            case 40: {
              addReaderId(input.readUInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addReaderId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              setTxStrength(input.readUInt32());
              break;
            }
            case 56: {
              setAreaId(input.readUInt32());
              break;
            }
            case 64: {
              setRoomId(input.readUInt32());
              break;
            }
            case 72: {
              setBuildingId(input.readUInt32());
              break;
            }
            case 80: {
              setInstallationId(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional sint32 x = 1;
      public boolean hasX() {
        return result.hasX();
      }
      public int getX() {
        return result.getX();
      }
      public Builder setX(int value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0;
        return this;
      }
      
      // optional sint32 y = 2;
      public boolean hasY() {
        return result.hasY();
      }
      public int getY() {
        return result.getY();
      }
      public Builder setY(int value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0;
        return this;
      }
      
      // optional sint32 z = 3;
      public boolean hasZ() {
        return result.hasZ();
      }
      public int getZ() {
        return result.getZ();
      }
      public Builder setZ(int value) {
        result.hasZ = true;
        result.z_ = value;
        return this;
      }
      public Builder clearZ() {
        result.hasZ = false;
        result.z_ = 0;
        return this;
      }
      
      // optional .ObUnit unit = 4;
      public boolean hasUnit() {
        return result.hasUnit();
      }
      public Openbeacon.ObUnit getUnit() {
        return result.getUnit();
      }
      public Builder setUnit(Openbeacon.ObUnit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUnit = true;
        result.unit_ = value;
        return this;
      }
      public Builder clearUnit() {
        result.hasUnit = false;
        result.unit_ = Openbeacon.ObUnit.OB_UNIT_NONE;
        return this;
      }
      
      // repeated uint32 reader_id = 5;
      public java.util.List<java.lang.Integer> getReaderIdList() {
        return java.util.Collections.unmodifiableList(result.readerId_);
      }
      public int getReaderIdCount() {
        return result.getReaderIdCount();
      }
      public int getReaderId(int index) {
        return result.getReaderId(index);
      }
      public Builder setReaderId(int index, int value) {
        result.readerId_.set(index, value);
        return this;
      }
      public Builder addReaderId(int value) {
        if (result.readerId_.isEmpty()) {
          result.readerId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.readerId_.add(value);
        return this;
      }
      public Builder addAllReaderId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.readerId_.isEmpty()) {
          result.readerId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.readerId_);
        return this;
      }
      public Builder clearReaderId() {
        result.readerId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 tx_strength = 6;
      public boolean hasTxStrength() {
        return result.hasTxStrength();
      }
      public int getTxStrength() {
        return result.getTxStrength();
      }
      public Builder setTxStrength(int value) {
        result.hasTxStrength = true;
        result.txStrength_ = value;
        return this;
      }
      public Builder clearTxStrength() {
        result.hasTxStrength = false;
        result.txStrength_ = 0;
        return this;
      }
      
      // optional uint32 area_id = 7;
      public boolean hasAreaId() {
        return result.hasAreaId();
      }
      public int getAreaId() {
        return result.getAreaId();
      }
      public Builder setAreaId(int value) {
        result.hasAreaId = true;
        result.areaId_ = value;
        return this;
      }
      public Builder clearAreaId() {
        result.hasAreaId = false;
        result.areaId_ = 0;
        return this;
      }
      
      // optional uint32 room_id = 8;
      public boolean hasRoomId() {
        return result.hasRoomId();
      }
      public int getRoomId() {
        return result.getRoomId();
      }
      public Builder setRoomId(int value) {
        result.hasRoomId = true;
        result.roomId_ = value;
        return this;
      }
      public Builder clearRoomId() {
        result.hasRoomId = false;
        result.roomId_ = 0;
        return this;
      }
      
      // optional uint32 building_id = 9;
      public boolean hasBuildingId() {
        return result.hasBuildingId();
      }
      public int getBuildingId() {
        return result.getBuildingId();
      }
      public Builder setBuildingId(int value) {
        result.hasBuildingId = true;
        result.buildingId_ = value;
        return this;
      }
      public Builder clearBuildingId() {
        result.hasBuildingId = false;
        result.buildingId_ = 0;
        return this;
      }
      
      // optional uint32 installation_id = 10;
      public boolean hasInstallationId() {
        return result.hasInstallationId();
      }
      public int getInstallationId() {
        return result.getInstallationId();
      }
      public Builder setInstallationId(int value) {
        result.hasInstallationId = true;
        result.installationId_ = value;
        return this;
      }
      public Builder clearInstallationId() {
        result.hasInstallationId = false;
        result.installationId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObTracking)
    }
    
    static {
      defaultInstance = new ObTracking(true);
      Openbeacon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObTracking)
  }
  
  public static final class ObProximityTagPower extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ObProximityTagPower> {
    // Use ObProximityTagPower.newBuilder() to construct.
    private ObProximityTagPower() {
      initFields();
    }
    private ObProximityTagPower(boolean noInit) {}
    
    private static final ObProximityTagPower defaultInstance;
    public static ObProximityTagPower getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObProximityTagPower getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openbeacon.internal_static_ObProximityTagPower_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openbeacon.internal_static_ObProximityTagPower_fieldAccessorTable;
    }
    
    // optional uint32 power = 1;
    public static final int POWER_FIELD_NUMBER = 1;
    private boolean hasPower;
    private int power_ = 0;
    public boolean hasPower() { return hasPower; }
    public int getPower() { return power_; }
    
    // optional uint32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasPower()) {
        output.writeUInt32(1, getPower());
      }
      if (hasCount()) {
        output.writeUInt32(2, getCount());
      }
      extensionWriter.writeUntil(128, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPower()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getPower());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getCount());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Openbeacon.ObProximityTagPower parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityTagPower parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityTagPower parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityTagPower parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Openbeacon.ObProximityTagPower prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Openbeacon.ObProximityTagPower, Builder> {
      private Openbeacon.ObProximityTagPower result;
      
      // Construct using Openbeacon.ObProximityTagPower.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Openbeacon.ObProximityTagPower();
        return builder;
      }
      
      protected Openbeacon.ObProximityTagPower internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Openbeacon.ObProximityTagPower();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openbeacon.ObProximityTagPower.getDescriptor();
      }
      
      public Openbeacon.ObProximityTagPower getDefaultInstanceForType() {
        return Openbeacon.ObProximityTagPower.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Openbeacon.ObProximityTagPower build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Openbeacon.ObProximityTagPower buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Openbeacon.ObProximityTagPower buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Openbeacon.ObProximityTagPower returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openbeacon.ObProximityTagPower) {
          return mergeFrom((Openbeacon.ObProximityTagPower)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Openbeacon.ObProximityTagPower other) {
        if (other == Openbeacon.ObProximityTagPower.getDefaultInstance()) return this;
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPower(input.readUInt32());
              break;
            }
            case 16: {
              setCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 power = 1;
      public boolean hasPower() {
        return result.hasPower();
      }
      public int getPower() {
        return result.getPower();
      }
      public Builder setPower(int value) {
        result.hasPower = true;
        result.power_ = value;
        return this;
      }
      public Builder clearPower() {
        result.hasPower = false;
        result.power_ = 0;
        return this;
      }
      
      // optional uint32 count = 2;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObProximityTagPower)
    }
    
    static {
      defaultInstance = new ObProximityTagPower(true);
      Openbeacon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObProximityTagPower)
  }
  
  public static final class ObProximityTag extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ObProximityTag> {
    // Use ObProximityTag.newBuilder() to construct.
    private ObProximityTag() {
      initFields();
    }
    private ObProximityTag(boolean noInit) {}
    
    private static final ObProximityTag defaultInstance;
    public static ObProximityTag getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObProximityTag getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openbeacon.internal_static_ObProximityTag_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openbeacon.internal_static_ObProximityTag_fieldAccessorTable;
    }
    
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // repeated .ObProximityTagPower power = 2;
    public static final int POWER_FIELD_NUMBER = 2;
    private java.util.List<Openbeacon.ObProximityTagPower> power_ =
      java.util.Collections.emptyList();
    public java.util.List<Openbeacon.ObProximityTagPower> getPowerList() {
      return power_;
    }
    public int getPowerCount() { return power_.size(); }
    public Openbeacon.ObProximityTagPower getPower(int index) {
      return power_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      for (Openbeacon.ObProximityTagPower element : getPowerList()) {
        if (!element.isInitialized()) return false;
      }
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasId()) {
        output.writeUInt32(1, getId());
      }
      for (Openbeacon.ObProximityTagPower element : getPowerList()) {
        output.writeMessage(2, element);
      }
      extensionWriter.writeUntil(128, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getId());
      }
      for (Openbeacon.ObProximityTagPower element : getPowerList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Openbeacon.ObProximityTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Openbeacon.ObProximityTag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Openbeacon.ObProximityTag, Builder> {
      private Openbeacon.ObProximityTag result;
      
      // Construct using Openbeacon.ObProximityTag.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Openbeacon.ObProximityTag();
        return builder;
      }
      
      protected Openbeacon.ObProximityTag internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Openbeacon.ObProximityTag();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openbeacon.ObProximityTag.getDescriptor();
      }
      
      public Openbeacon.ObProximityTag getDefaultInstanceForType() {
        return Openbeacon.ObProximityTag.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Openbeacon.ObProximityTag build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Openbeacon.ObProximityTag buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Openbeacon.ObProximityTag buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.power_ != java.util.Collections.EMPTY_LIST) {
          result.power_ =
            java.util.Collections.unmodifiableList(result.power_);
        }
        Openbeacon.ObProximityTag returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openbeacon.ObProximityTag) {
          return mergeFrom((Openbeacon.ObProximityTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Openbeacon.ObProximityTag other) {
        if (other == Openbeacon.ObProximityTag.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.power_.isEmpty()) {
          if (result.power_.isEmpty()) {
            result.power_ = new java.util.ArrayList<Openbeacon.ObProximityTagPower>();
          }
          result.power_.addAll(other.power_);
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readUInt32());
              break;
            }
            case 18: {
              Openbeacon.ObProximityTagPower.Builder subBuilder = Openbeacon.ObProximityTagPower.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPower(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // repeated .ObProximityTagPower power = 2;
      public java.util.List<Openbeacon.ObProximityTagPower> getPowerList() {
        return java.util.Collections.unmodifiableList(result.power_);
      }
      public int getPowerCount() {
        return result.getPowerCount();
      }
      public Openbeacon.ObProximityTagPower getPower(int index) {
        return result.getPower(index);
      }
      public Builder setPower(int index, Openbeacon.ObProximityTagPower value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.power_.set(index, value);
        return this;
      }
      public Builder setPower(int index, Openbeacon.ObProximityTagPower.Builder builderForValue) {
        result.power_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPower(Openbeacon.ObProximityTagPower value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.power_.isEmpty()) {
          result.power_ = new java.util.ArrayList<Openbeacon.ObProximityTagPower>();
        }
        result.power_.add(value);
        return this;
      }
      public Builder addPower(Openbeacon.ObProximityTagPower.Builder builderForValue) {
        if (result.power_.isEmpty()) {
          result.power_ = new java.util.ArrayList<Openbeacon.ObProximityTagPower>();
        }
        result.power_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPower(
          java.lang.Iterable<? extends Openbeacon.ObProximityTagPower> values) {
        if (result.power_.isEmpty()) {
          result.power_ = new java.util.ArrayList<Openbeacon.ObProximityTagPower>();
        }
        super.addAll(values, result.power_);
        return this;
      }
      public Builder clearPower() {
        result.power_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObProximityTag)
    }
    
    static {
      defaultInstance = new ObProximityTag(true);
      Openbeacon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObProximityTag)
  }
  
  public static final class ObProximityLog extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ObProximityLog> {
    // Use ObProximityLog.newBuilder() to construct.
    private ObProximityLog() {
      initFields();
    }
    private ObProximityLog(boolean noInit) {}
    
    private static final ObProximityLog defaultInstance;
    public static ObProximityLog getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObProximityLog getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openbeacon.internal_static_ObProximityLog_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openbeacon.internal_static_ObProximityLog_fieldAccessorTable;
    }
    
    // required uint32 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private boolean hasTime;
    private int time_ = 0;
    public boolean hasTime() { return hasTime; }
    public int getTime() { return time_; }
    
    // required uint32 duration = 2;
    public static final int DURATION_FIELD_NUMBER = 2;
    private boolean hasDuration;
    private int duration_ = 0;
    public boolean hasDuration() { return hasDuration; }
    public int getDuration() { return duration_; }
    
    // repeated .ObProximityTag tag = 3;
    public static final int TAG_FIELD_NUMBER = 3;
    private java.util.List<Openbeacon.ObProximityTag> tag_ =
      java.util.Collections.emptyList();
    public java.util.List<Openbeacon.ObProximityTag> getTagList() {
      return tag_;
    }
    public int getTagCount() { return tag_.size(); }
    public Openbeacon.ObProximityTag getTag(int index) {
      return tag_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTime) return false;
      if (!hasDuration) return false;
      for (Openbeacon.ObProximityTag element : getTagList()) {
        if (!element.isInitialized()) return false;
      }
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasTime()) {
        output.writeUInt32(1, getTime());
      }
      if (hasDuration()) {
        output.writeUInt32(2, getDuration());
      }
      for (Openbeacon.ObProximityTag element : getTagList()) {
        output.writeMessage(3, element);
      }
      extensionWriter.writeUntil(128, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getTime());
      }
      if (hasDuration()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getDuration());
      }
      for (Openbeacon.ObProximityTag element : getTagList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Openbeacon.ObProximityLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObProximityLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObProximityLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObProximityLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Openbeacon.ObProximityLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Openbeacon.ObProximityLog, Builder> {
      private Openbeacon.ObProximityLog result;
      
      // Construct using Openbeacon.ObProximityLog.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Openbeacon.ObProximityLog();
        return builder;
      }
      
      protected Openbeacon.ObProximityLog internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Openbeacon.ObProximityLog();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openbeacon.ObProximityLog.getDescriptor();
      }
      
      public Openbeacon.ObProximityLog getDefaultInstanceForType() {
        return Openbeacon.ObProximityLog.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Openbeacon.ObProximityLog build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Openbeacon.ObProximityLog buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Openbeacon.ObProximityLog buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.tag_ != java.util.Collections.EMPTY_LIST) {
          result.tag_ =
            java.util.Collections.unmodifiableList(result.tag_);
        }
        Openbeacon.ObProximityLog returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openbeacon.ObProximityLog) {
          return mergeFrom((Openbeacon.ObProximityLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Openbeacon.ObProximityLog other) {
        if (other == Openbeacon.ObProximityLog.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (!other.tag_.isEmpty()) {
          if (result.tag_.isEmpty()) {
            result.tag_ = new java.util.ArrayList<Openbeacon.ObProximityTag>();
          }
          result.tag_.addAll(other.tag_);
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTime(input.readUInt32());
              break;
            }
            case 16: {
              setDuration(input.readUInt32());
              break;
            }
            case 26: {
              Openbeacon.ObProximityTag.Builder subBuilder = Openbeacon.ObProximityTag.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTag(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required uint32 time = 1;
      public boolean hasTime() {
        return result.hasTime();
      }
      public int getTime() {
        return result.getTime();
      }
      public Builder setTime(int value) {
        result.hasTime = true;
        result.time_ = value;
        return this;
      }
      public Builder clearTime() {
        result.hasTime = false;
        result.time_ = 0;
        return this;
      }
      
      // required uint32 duration = 2;
      public boolean hasDuration() {
        return result.hasDuration();
      }
      public int getDuration() {
        return result.getDuration();
      }
      public Builder setDuration(int value) {
        result.hasDuration = true;
        result.duration_ = value;
        return this;
      }
      public Builder clearDuration() {
        result.hasDuration = false;
        result.duration_ = 0;
        return this;
      }
      
      // repeated .ObProximityTag tag = 3;
      public java.util.List<Openbeacon.ObProximityTag> getTagList() {
        return java.util.Collections.unmodifiableList(result.tag_);
      }
      public int getTagCount() {
        return result.getTagCount();
      }
      public Openbeacon.ObProximityTag getTag(int index) {
        return result.getTag(index);
      }
      public Builder setTag(int index, Openbeacon.ObProximityTag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.tag_.set(index, value);
        return this;
      }
      public Builder setTag(int index, Openbeacon.ObProximityTag.Builder builderForValue) {
        result.tag_.set(index, builderForValue.build());
        return this;
      }
      public Builder addTag(Openbeacon.ObProximityTag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.tag_.isEmpty()) {
          result.tag_ = new java.util.ArrayList<Openbeacon.ObProximityTag>();
        }
        result.tag_.add(value);
        return this;
      }
      public Builder addTag(Openbeacon.ObProximityTag.Builder builderForValue) {
        if (result.tag_.isEmpty()) {
          result.tag_ = new java.util.ArrayList<Openbeacon.ObProximityTag>();
        }
        result.tag_.add(builderForValue.build());
        return this;
      }
      public Builder addAllTag(
          java.lang.Iterable<? extends Openbeacon.ObProximityTag> values) {
        if (result.tag_.isEmpty()) {
          result.tag_ = new java.util.ArrayList<Openbeacon.ObProximityTag>();
        }
        super.addAll(values, result.tag_);
        return this;
      }
      public Builder clearTag() {
        result.tag_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObProximityLog)
    }
    
    static {
      defaultInstance = new ObProximityLog(true);
      Openbeacon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObProximityLog)
  }
  
  public static final class ObTag extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ObTag> {
    // Use ObTag.newBuilder() to construct.
    private ObTag() {
      initFields();
    }
    private ObTag(boolean noInit) {}
    
    private static final ObTag defaultInstance;
    public static ObTag getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObTag getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openbeacon.internal_static_ObTag_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openbeacon.internal_static_ObTag_fieldAccessorTable;
    }
    
    // optional uint32 tag_id = 1;
    public static final int TAG_ID_FIELD_NUMBER = 1;
    private boolean hasTagId;
    private int tagId_ = 0;
    public boolean hasTagId() { return hasTagId; }
    public int getTagId() { return tagId_; }
    
    // optional uint32 tag_time = 2;
    public static final int TAG_TIME_FIELD_NUMBER = 2;
    private boolean hasTagTime;
    private int tagTime_ = 0;
    public boolean hasTagTime() { return hasTagTime; }
    public int getTagTime() { return tagTime_; }
    
    // optional uint32 tag_power_cycles = 3;
    public static final int TAG_POWER_CYCLES_FIELD_NUMBER = 3;
    private boolean hasTagPowerCycles;
    private int tagPowerCycles_ = 0;
    public boolean hasTagPowerCycles() { return hasTagPowerCycles; }
    public int getTagPowerCycles() { return tagPowerCycles_; }
    
    // optional uint32 tag_strength = 4;
    public static final int TAG_STRENGTH_FIELD_NUMBER = 4;
    private boolean hasTagStrength;
    private int tagStrength_ = 0;
    public boolean hasTagStrength() { return hasTagStrength; }
    public int getTagStrength() { return tagStrength_; }
    
    // repeated uint32 forwarder_id = 5;
    public static final int FORWARDER_ID_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> forwarderId_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getForwarderIdList() {
      return forwarderId_;
    }
    public int getForwarderIdCount() { return forwarderId_.size(); }
    public int getForwarderId(int index) {
      return forwarderId_.get(index);
    }
    
    // optional uint32 forwarder_storage_time = 6;
    public static final int FORWARDER_STORAGE_TIME_FIELD_NUMBER = 6;
    private boolean hasForwarderStorageTime;
    private int forwarderStorageTime_ = 0;
    public boolean hasForwarderStorageTime() { return hasForwarderStorageTime; }
    public int getForwarderStorageTime() { return forwarderStorageTime_; }
    
    // optional uint64 rx_time = 7;
    public static final int RX_TIME_FIELD_NUMBER = 7;
    private boolean hasRxTime;
    private long rxTime_ = 0L;
    public boolean hasRxTime() { return hasRxTime; }
    public long getRxTime() { return rxTime_; }
    
    // optional .ObTracking tracking = 14;
    public static final int TRACKING_FIELD_NUMBER = 14;
    private boolean hasTracking;
    private Openbeacon.ObTracking tracking_;
    public boolean hasTracking() { return hasTracking; }
    public Openbeacon.ObTracking getTracking() { return tracking_; }
    
    // repeated .ObProximityLog proximity = 15;
    public static final int PROXIMITY_FIELD_NUMBER = 15;
    private java.util.List<Openbeacon.ObProximityLog> proximity_ =
      java.util.Collections.emptyList();
    public java.util.List<Openbeacon.ObProximityLog> getProximityList() {
      return proximity_;
    }
    public int getProximityCount() { return proximity_.size(); }
    public Openbeacon.ObProximityLog getProximity(int index) {
      return proximity_.get(index);
    }
    
    private void initFields() {
      tracking_ = Openbeacon.ObTracking.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasTracking()) {
        if (!getTracking().isInitialized()) return false;
      }
      for (Openbeacon.ObProximityLog element : getProximityList()) {
        if (!element.isInitialized()) return false;
      }
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasTagId()) {
        output.writeUInt32(1, getTagId());
      }
      if (hasTagTime()) {
        output.writeUInt32(2, getTagTime());
      }
      if (hasTagPowerCycles()) {
        output.writeUInt32(3, getTagPowerCycles());
      }
      if (hasTagStrength()) {
        output.writeUInt32(4, getTagStrength());
      }
      for (int element : getForwarderIdList()) {
        output.writeUInt32(5, element);
      }
      if (hasForwarderStorageTime()) {
        output.writeUInt32(6, getForwarderStorageTime());
      }
      if (hasRxTime()) {
        output.writeUInt64(7, getRxTime());
      }
      if (hasTracking()) {
        output.writeMessage(14, getTracking());
      }
      for (Openbeacon.ObProximityLog element : getProximityList()) {
        output.writeMessage(15, element);
      }
      extensionWriter.writeUntil(128, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTagId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getTagId());
      }
      if (hasTagTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getTagTime());
      }
      if (hasTagPowerCycles()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getTagPowerCycles());
      }
      if (hasTagStrength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getTagStrength());
      }
      {
        int dataSize = 0;
        for (int element : getForwarderIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getForwarderIdList().size();
      }
      if (hasForwarderStorageTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getForwarderStorageTime());
      }
      if (hasRxTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, getRxTime());
      }
      if (hasTracking()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getTracking());
      }
      for (Openbeacon.ObProximityLog element : getProximityList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, element);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Openbeacon.ObTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Openbeacon.ObTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Openbeacon.ObTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Openbeacon.ObTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Openbeacon.ObTag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Openbeacon.ObTag, Builder> {
      private Openbeacon.ObTag result;
      
      // Construct using Openbeacon.ObTag.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Openbeacon.ObTag();
        return builder;
      }
      
      protected Openbeacon.ObTag internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Openbeacon.ObTag();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openbeacon.ObTag.getDescriptor();
      }
      
      public Openbeacon.ObTag getDefaultInstanceForType() {
        return Openbeacon.ObTag.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Openbeacon.ObTag build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Openbeacon.ObTag buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Openbeacon.ObTag buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.forwarderId_ != java.util.Collections.EMPTY_LIST) {
          result.forwarderId_ =
            java.util.Collections.unmodifiableList(result.forwarderId_);
        }
        if (result.proximity_ != java.util.Collections.EMPTY_LIST) {
          result.proximity_ =
            java.util.Collections.unmodifiableList(result.proximity_);
        }
        Openbeacon.ObTag returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openbeacon.ObTag) {
          return mergeFrom((Openbeacon.ObTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Openbeacon.ObTag other) {
        if (other == Openbeacon.ObTag.getDefaultInstance()) return this;
        if (other.hasTagId()) {
          setTagId(other.getTagId());
        }
        if (other.hasTagTime()) {
          setTagTime(other.getTagTime());
        }
        if (other.hasTagPowerCycles()) {
          setTagPowerCycles(other.getTagPowerCycles());
        }
        if (other.hasTagStrength()) {
          setTagStrength(other.getTagStrength());
        }
        if (!other.forwarderId_.isEmpty()) {
          if (result.forwarderId_.isEmpty()) {
            result.forwarderId_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.forwarderId_.addAll(other.forwarderId_);
        }
        if (other.hasForwarderStorageTime()) {
          setForwarderStorageTime(other.getForwarderStorageTime());
        }
        if (other.hasRxTime()) {
          setRxTime(other.getRxTime());
        }
        if (other.hasTracking()) {
          mergeTracking(other.getTracking());
        }
        if (!other.proximity_.isEmpty()) {
          if (result.proximity_.isEmpty()) {
            result.proximity_ = new java.util.ArrayList<Openbeacon.ObProximityLog>();
          }
          result.proximity_.addAll(other.proximity_);
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTagId(input.readUInt32());
              break;
            }
            case 16: {
              setTagTime(input.readUInt32());
              break;
            }
            case 24: {
              setTagPowerCycles(input.readUInt32());
              break;
            }
            case 32: {
              setTagStrength(input.readUInt32());
              break;
            }
            case 40: {
              addForwarderId(input.readUInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addForwarderId(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              setForwarderStorageTime(input.readUInt32());
              break;
            }
            case 56: {
              setRxTime(input.readUInt64());
              break;
            }
            case 114: {
              Openbeacon.ObTracking.Builder subBuilder = Openbeacon.ObTracking.newBuilder();
              if (hasTracking()) {
                subBuilder.mergeFrom(getTracking());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTracking(subBuilder.buildPartial());
              break;
            }
            case 122: {
              Openbeacon.ObProximityLog.Builder subBuilder = Openbeacon.ObProximityLog.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProximity(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 tag_id = 1;
      public boolean hasTagId() {
        return result.hasTagId();
      }
      public int getTagId() {
        return result.getTagId();
      }
      public Builder setTagId(int value) {
        result.hasTagId = true;
        result.tagId_ = value;
        return this;
      }
      public Builder clearTagId() {
        result.hasTagId = false;
        result.tagId_ = 0;
        return this;
      }
      
      // optional uint32 tag_time = 2;
      public boolean hasTagTime() {
        return result.hasTagTime();
      }
      public int getTagTime() {
        return result.getTagTime();
      }
      public Builder setTagTime(int value) {
        result.hasTagTime = true;
        result.tagTime_ = value;
        return this;
      }
      public Builder clearTagTime() {
        result.hasTagTime = false;
        result.tagTime_ = 0;
        return this;
      }
      
      // optional uint32 tag_power_cycles = 3;
      public boolean hasTagPowerCycles() {
        return result.hasTagPowerCycles();
      }
      public int getTagPowerCycles() {
        return result.getTagPowerCycles();
      }
      public Builder setTagPowerCycles(int value) {
        result.hasTagPowerCycles = true;
        result.tagPowerCycles_ = value;
        return this;
      }
      public Builder clearTagPowerCycles() {
        result.hasTagPowerCycles = false;
        result.tagPowerCycles_ = 0;
        return this;
      }
      
      // optional uint32 tag_strength = 4;
      public boolean hasTagStrength() {
        return result.hasTagStrength();
      }
      public int getTagStrength() {
        return result.getTagStrength();
      }
      public Builder setTagStrength(int value) {
        result.hasTagStrength = true;
        result.tagStrength_ = value;
        return this;
      }
      public Builder clearTagStrength() {
        result.hasTagStrength = false;
        result.tagStrength_ = 0;
        return this;
      }
      
      // repeated uint32 forwarder_id = 5;
      public java.util.List<java.lang.Integer> getForwarderIdList() {
        return java.util.Collections.unmodifiableList(result.forwarderId_);
      }
      public int getForwarderIdCount() {
        return result.getForwarderIdCount();
      }
      public int getForwarderId(int index) {
        return result.getForwarderId(index);
      }
      public Builder setForwarderId(int index, int value) {
        result.forwarderId_.set(index, value);
        return this;
      }
      public Builder addForwarderId(int value) {
        if (result.forwarderId_.isEmpty()) {
          result.forwarderId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.forwarderId_.add(value);
        return this;
      }
      public Builder addAllForwarderId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.forwarderId_.isEmpty()) {
          result.forwarderId_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.forwarderId_);
        return this;
      }
      public Builder clearForwarderId() {
        result.forwarderId_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 forwarder_storage_time = 6;
      public boolean hasForwarderStorageTime() {
        return result.hasForwarderStorageTime();
      }
      public int getForwarderStorageTime() {
        return result.getForwarderStorageTime();
      }
      public Builder setForwarderStorageTime(int value) {
        result.hasForwarderStorageTime = true;
        result.forwarderStorageTime_ = value;
        return this;
      }
      public Builder clearForwarderStorageTime() {
        result.hasForwarderStorageTime = false;
        result.forwarderStorageTime_ = 0;
        return this;
      }
      
      // optional uint64 rx_time = 7;
      public boolean hasRxTime() {
        return result.hasRxTime();
      }
      public long getRxTime() {
        return result.getRxTime();
      }
      public Builder setRxTime(long value) {
        result.hasRxTime = true;
        result.rxTime_ = value;
        return this;
      }
      public Builder clearRxTime() {
        result.hasRxTime = false;
        result.rxTime_ = 0L;
        return this;
      }
      
      // optional .ObTracking tracking = 14;
      public boolean hasTracking() {
        return result.hasTracking();
      }
      public Openbeacon.ObTracking getTracking() {
        return result.getTracking();
      }
      public Builder setTracking(Openbeacon.ObTracking value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTracking = true;
        result.tracking_ = value;
        return this;
      }
      public Builder setTracking(Openbeacon.ObTracking.Builder builderForValue) {
        result.hasTracking = true;
        result.tracking_ = builderForValue.build();
        return this;
      }
      public Builder mergeTracking(Openbeacon.ObTracking value) {
        if (result.hasTracking() &&
            result.tracking_ != Openbeacon.ObTracking.getDefaultInstance()) {
          result.tracking_ =
            Openbeacon.ObTracking.newBuilder(result.tracking_).mergeFrom(value).buildPartial();
        } else {
          result.tracking_ = value;
        }
        result.hasTracking = true;
        return this;
      }
      public Builder clearTracking() {
        result.hasTracking = false;
        result.tracking_ = Openbeacon.ObTracking.getDefaultInstance();
        return this;
      }
      
      // repeated .ObProximityLog proximity = 15;
      public java.util.List<Openbeacon.ObProximityLog> getProximityList() {
        return java.util.Collections.unmodifiableList(result.proximity_);
      }
      public int getProximityCount() {
        return result.getProximityCount();
      }
      public Openbeacon.ObProximityLog getProximity(int index) {
        return result.getProximity(index);
      }
      public Builder setProximity(int index, Openbeacon.ObProximityLog value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.proximity_.set(index, value);
        return this;
      }
      public Builder setProximity(int index, Openbeacon.ObProximityLog.Builder builderForValue) {
        result.proximity_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProximity(Openbeacon.ObProximityLog value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.proximity_.isEmpty()) {
          result.proximity_ = new java.util.ArrayList<Openbeacon.ObProximityLog>();
        }
        result.proximity_.add(value);
        return this;
      }
      public Builder addProximity(Openbeacon.ObProximityLog.Builder builderForValue) {
        if (result.proximity_.isEmpty()) {
          result.proximity_ = new java.util.ArrayList<Openbeacon.ObProximityLog>();
        }
        result.proximity_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProximity(
          java.lang.Iterable<? extends Openbeacon.ObProximityLog> values) {
        if (result.proximity_.isEmpty()) {
          result.proximity_ = new java.util.ArrayList<Openbeacon.ObProximityLog>();
        }
        super.addAll(values, result.proximity_);
        return this;
      }
      public Builder clearProximity() {
        result.proximity_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObTag)
    }
    
    static {
      defaultInstance = new ObTag(true);
      Openbeacon.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObTag)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObTracking_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObTracking_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObProximityTagPower_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObProximityTagPower_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObProximityTag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObProximityTag_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObProximityLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObProximityLog_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObTag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObTag_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020openbeacon.proto\"\303\001\n\nObTracking\022\t\n\001x\030\001" +
      " \001(\021\022\t\n\001y\030\002 \001(\021\022\t\n\001z\030\003 \001(\021\022\025\n\004unit\030\004 \001(\016" +
      "2\007.ObUnit\022\021\n\treader_id\030\005 \003(\r\022\023\n\013tx_stren" +
      "gth\030\006 \001(\r\022\017\n\007area_id\030\007 \001(\r\022\017\n\007room_id\030\010 " +
      "\001(\r\022\023\n\013building_id\030\t \001(\r\022\027\n\017installation" +
      "_id\030\n \001(\r*\005\010d\020\200\001\":\n\023ObProximityTagPower\022" +
      "\r\n\005power\030\001 \001(\r\022\r\n\005count\030\002 \001(\r*\005\010d\020\200\001\"H\n\016" +
      "ObProximityTag\022\n\n\002id\030\001 \002(\r\022#\n\005power\030\002 \003(" +
      "\0132\024.ObProximityTagPower*\005\010d\020\200\001\"U\n\016ObProx" +
      "imityLog\022\014\n\004time\030\001 \002(\r\022\020\n\010duration\030\002 \002(\r",
      "\022\034\n\003tag\030\003 \003(\0132\017.ObProximityTag*\005\010d\020\200\001\"\352\001" +
      "\n\005ObTag\022\016\n\006tag_id\030\001 \001(\r\022\020\n\010tag_time\030\002 \001(" +
      "\r\022\030\n\020tag_power_cycles\030\003 \001(\r\022\024\n\014tag_stren" +
      "gth\030\004 \001(\r\022\024\n\014forwarder_id\030\005 \003(\r\022\036\n\026forwa" +
      "rder_storage_time\030\006 \001(\r\022\017\n\007rx_time\030\007 \001(\004" +
      "\022\035\n\010tracking\030\016 \001(\0132\013.ObTracking\022\"\n\tproxi" +
      "mity\030\017 \003(\0132\017.ObProximityLog*\005\010d\020\200\001*\246\001\n\006O" +
      "bUnit\022\020\n\014OB_UNIT_NONE\020\000\022\021\n\rOB_UNIT_PIXEL" +
      "\020\001\022\026\n\022OB_UNIT_MILLIMETER\020\002\022\026\n\022OB_UNIT_CE" +
      "NTIMETER\020\003\022\021\n\rOB_UNIT_METER\020\004\022\020\n\014OB_UNIT",
      "_INCH\020\005\022\020\n\014OB_UNIT_FEET\020\006\022\020\n\014OB_UNIT_YAR" +
      "D\020\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ObTracking_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ObTracking_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObTracking_descriptor,
              new java.lang.String[] { "X", "Y", "Z", "Unit", "ReaderId", "TxStrength", "AreaId", "RoomId", "BuildingId", "InstallationId", },
              Openbeacon.ObTracking.class,
              Openbeacon.ObTracking.Builder.class);
          internal_static_ObProximityTagPower_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ObProximityTagPower_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObProximityTagPower_descriptor,
              new java.lang.String[] { "Power", "Count", },
              Openbeacon.ObProximityTagPower.class,
              Openbeacon.ObProximityTagPower.Builder.class);
          internal_static_ObProximityTag_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ObProximityTag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObProximityTag_descriptor,
              new java.lang.String[] { "Id", "Power", },
              Openbeacon.ObProximityTag.class,
              Openbeacon.ObProximityTag.Builder.class);
          internal_static_ObProximityLog_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ObProximityLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObProximityLog_descriptor,
              new java.lang.String[] { "Time", "Duration", "Tag", },
              Openbeacon.ObProximityLog.class,
              Openbeacon.ObProximityLog.Builder.class);
          internal_static_ObTag_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ObTag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObTag_descriptor,
              new java.lang.String[] { "TagId", "TagTime", "TagPowerCycles", "TagStrength", "ForwarderId", "ForwarderStorageTime", "RxTime", "Tracking", "Proximity", },
              Openbeacon.ObTag.class,
              Openbeacon.ObTag.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
