# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='openbeacon.proto',
  package='',
  serialized_pb='\n\x10openbeacon.proto\"\xc3\x01\n\nObTracking\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\x12\t\n\x01z\x18\x03 \x01(\x11\x12\x15\n\x04unit\x18\x04 \x01(\x0e\x32\x07.ObUnit\x12\x11\n\treader_id\x18\x05 \x03(\r\x12\x13\n\x0btx_strength\x18\x06 \x01(\r\x12\x0f\n\x07\x61rea_id\x18\x07 \x01(\r\x12\x0f\n\x07room_id\x18\x08 \x01(\r\x12\x13\n\x0b\x62uilding_id\x18\t \x01(\r\x12\x17\n\x0finstallation_id\x18\n \x01(\r*\x05\x08\x64\x10\x80\x01\":\n\x13ObProximityTagPower\x12\r\n\x05power\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r*\x05\x08\x64\x10\x80\x01\"H\n\x0eObProximityTag\x12\n\n\x02id\x18\x01 \x02(\r\x12#\n\x05power\x18\x02 \x03(\x0b\x32\x14.ObProximityTagPower*\x05\x08\x64\x10\x80\x01\"U\n\x0eObProximityLog\x12\x0c\n\x04time\x18\x01 \x02(\r\x12\x10\n\x08\x64uration\x18\x02 \x02(\r\x12\x1c\n\x03tag\x18\x03 \x03(\x0b\x32\x0f.ObProximityTag*\x05\x08\x64\x10\x80\x01\"\xea\x01\n\x05ObTag\x12\x0e\n\x06tag_id\x18\x01 \x01(\r\x12\x10\n\x08tag_time\x18\x02 \x01(\r\x12\x18\n\x10tag_power_cycles\x18\x03 \x01(\r\x12\x14\n\x0ctag_strength\x18\x04 \x01(\r\x12\x14\n\x0c\x66orwarder_id\x18\x05 \x03(\r\x12\x1e\n\x16\x66orwarder_storage_time\x18\x06 \x01(\r\x12\x0f\n\x07rx_time\x18\x07 \x01(\x04\x12\x1d\n\x08tracking\x18\x0e \x01(\x0b\x32\x0b.ObTracking\x12\"\n\tproximity\x18\x0f \x03(\x0b\x32\x0f.ObProximityLog*\x05\x08\x64\x10\x80\x01*\xa6\x01\n\x06ObUnit\x12\x10\n\x0cOB_UNIT_NONE\x10\x00\x12\x11\n\rOB_UNIT_PIXEL\x10\x01\x12\x16\n\x12OB_UNIT_MILLIMETER\x10\x02\x12\x16\n\x12OB_UNIT_CENTIMETER\x10\x03\x12\x11\n\rOB_UNIT_METER\x10\x04\x12\x10\n\x0cOB_UNIT_INCH\x10\x05\x12\x10\n\x0cOB_UNIT_FEET\x10\x06\x12\x10\n\x0cOB_UNIT_YARD\x10\x07')

_OBUNIT = descriptor.EnumDescriptor(
  name='ObUnit',
  full_name='ObUnit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_NONE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_PIXEL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_MILLIMETER', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_CENTIMETER', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_METER', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_INCH', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_FEET', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OB_UNIT_YARD', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=677,
  serialized_end=843,
)


OB_UNIT_NONE = 0
OB_UNIT_PIXEL = 1
OB_UNIT_MILLIMETER = 2
OB_UNIT_CENTIMETER = 3
OB_UNIT_METER = 4
OB_UNIT_INCH = 5
OB_UNIT_FEET = 6
OB_UNIT_YARD = 7



_OBTRACKING = descriptor.Descriptor(
  name='ObTracking',
  full_name='ObTracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='ObTracking.x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='ObTracking.y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z', full_name='ObTracking.z', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unit', full_name='ObTracking.unit', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reader_id', full_name='ObTracking.reader_id', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tx_strength', full_name='ObTracking.tx_strength', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='area_id', full_name='ObTracking.area_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='room_id', full_name='ObTracking.room_id', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='building_id', full_name='ObTracking.building_id', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='installation_id', full_name='ObTracking.installation_id', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 128), ],
  serialized_start=21,
  serialized_end=216,
)


_OBPROXIMITYTAGPOWER = descriptor.Descriptor(
  name='ObProximityTagPower',
  full_name='ObProximityTagPower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='power', full_name='ObProximityTagPower.power', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='ObProximityTagPower.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 128), ],
  serialized_start=218,
  serialized_end=276,
)


_OBPROXIMITYTAG = descriptor.Descriptor(
  name='ObProximityTag',
  full_name='ObProximityTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ObProximityTag.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='power', full_name='ObProximityTag.power', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 128), ],
  serialized_start=278,
  serialized_end=350,
)


_OBPROXIMITYLOG = descriptor.Descriptor(
  name='ObProximityLog',
  full_name='ObProximityLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='ObProximityLog.time', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duration', full_name='ObProximityLog.duration', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag', full_name='ObProximityLog.tag', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 128), ],
  serialized_start=352,
  serialized_end=437,
)


_OBTAG = descriptor.Descriptor(
  name='ObTag',
  full_name='ObTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tag_id', full_name='ObTag.tag_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag_time', full_name='ObTag.tag_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag_power_cycles', full_name='ObTag.tag_power_cycles', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tag_strength', full_name='ObTag.tag_strength', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='forwarder_id', full_name='ObTag.forwarder_id', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='forwarder_storage_time', full_name='ObTag.forwarder_storage_time', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rx_time', full_name='ObTag.rx_time', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tracking', full_name='ObTag.tracking', index=7,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='proximity', full_name='ObTag.proximity', index=8,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 128), ],
  serialized_start=440,
  serialized_end=674,
)


_OBTRACKING.fields_by_name['unit'].enum_type = _OBUNIT
_OBPROXIMITYTAG.fields_by_name['power'].message_type = _OBPROXIMITYTAGPOWER
_OBPROXIMITYLOG.fields_by_name['tag'].message_type = _OBPROXIMITYTAG
_OBTAG.fields_by_name['tracking'].message_type = _OBTRACKING
_OBTAG.fields_by_name['proximity'].message_type = _OBPROXIMITYLOG

class ObTracking(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBTRACKING
  
  # @@protoc_insertion_point(class_scope:ObTracking)

class ObProximityTagPower(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBPROXIMITYTAGPOWER
  
  # @@protoc_insertion_point(class_scope:ObProximityTagPower)

class ObProximityTag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBPROXIMITYTAG
  
  # @@protoc_insertion_point(class_scope:ObProximityTag)

class ObProximityLog(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBPROXIMITYLOG
  
  # @@protoc_insertion_point(class_scope:ObProximityLog)

class ObTag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBTAG
  
  # @@protoc_insertion_point(class_scope:ObTag)

# @@protoc_insertion_point(module_scope)
