/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "openbeacon.pb-c.h"
void   ob_tracking__init
                     (ObTracking         *message)
{
  static ObTracking init_value = OB_TRACKING__INIT;
  *message = init_value;
}
size_t ob_tracking__get_packed_size
                     (const ObTracking *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tracking__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_tracking__pack
                     (const ObTracking *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tracking__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_tracking__pack_to_buffer
                     (const ObTracking *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tracking__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObTracking *
       ob_tracking__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObTracking *)
     protobuf_c_message_unpack (&ob_tracking__descriptor,
                                allocator, len, data);
}
void   ob_tracking__free_unpacked
                     (ObTracking *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tracking__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_proximity_tag_power__init
                     (ObProximityTagPower         *message)
{
  static ObProximityTagPower init_value = OB_PROXIMITY_TAG_POWER__INIT;
  *message = init_value;
}
size_t ob_proximity_tag_power__get_packed_size
                     (const ObProximityTagPower *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag_power__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_proximity_tag_power__pack
                     (const ObProximityTagPower *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag_power__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_proximity_tag_power__pack_to_buffer
                     (const ObProximityTagPower *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag_power__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObProximityTagPower *
       ob_proximity_tag_power__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObProximityTagPower *)
     protobuf_c_message_unpack (&ob_proximity_tag_power__descriptor,
                                allocator, len, data);
}
void   ob_proximity_tag_power__free_unpacked
                     (ObProximityTagPower *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag_power__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_proximity_tag__init
                     (ObProximityTag         *message)
{
  static ObProximityTag init_value = OB_PROXIMITY_TAG__INIT;
  *message = init_value;
}
size_t ob_proximity_tag__get_packed_size
                     (const ObProximityTag *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_proximity_tag__pack
                     (const ObProximityTag *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_proximity_tag__pack_to_buffer
                     (const ObProximityTag *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObProximityTag *
       ob_proximity_tag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObProximityTag *)
     protobuf_c_message_unpack (&ob_proximity_tag__descriptor,
                                allocator, len, data);
}
void   ob_proximity_tag__free_unpacked
                     (ObProximityTag *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_tag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_proximity_log__init
                     (ObProximityLog         *message)
{
  static ObProximityLog init_value = OB_PROXIMITY_LOG__INIT;
  *message = init_value;
}
size_t ob_proximity_log__get_packed_size
                     (const ObProximityLog *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_proximity_log__pack
                     (const ObProximityLog *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_proximity_log__pack_to_buffer
                     (const ObProximityLog *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObProximityLog *
       ob_proximity_log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObProximityLog *)
     protobuf_c_message_unpack (&ob_proximity_log__descriptor,
                                allocator, len, data);
}
void   ob_proximity_log__free_unpacked
                     (ObProximityLog *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_proximity_log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_tag__init
                     (ObTag         *message)
{
  static ObTag init_value = OB_TAG__INIT;
  *message = init_value;
}
size_t ob_tag__get_packed_size
                     (const ObTag *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_tag__pack
                     (const ObTag *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_tag__pack_to_buffer
                     (const ObTag *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObTag *
       ob_tag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObTag *)
     protobuf_c_message_unpack (&ob_tag__descriptor,
                                allocator, len, data);
}
void   ob_tag__free_unpacked
                     (ObTag *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ob_tag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ob_tracking__field_descriptors[10] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_x),
    PROTOBUF_C_OFFSETOF(ObTracking, x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_y),
    PROTOBUF_C_OFFSETOF(ObTracking, y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_z),
    PROTOBUF_C_OFFSETOF(ObTracking, z),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(ObTracking, has_unit),
    PROTOBUF_C_OFFSETOF(ObTracking, unit),
    &ob_unit__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reader_id",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, n_reader_id),
    PROTOBUF_C_OFFSETOF(ObTracking, reader_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_strength",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_tx_strength),
    PROTOBUF_C_OFFSETOF(ObTracking, tx_strength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "area_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_area_id),
    PROTOBUF_C_OFFSETOF(ObTracking, area_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "room_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_room_id),
    PROTOBUF_C_OFFSETOF(ObTracking, room_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "building_id",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_building_id),
    PROTOBUF_C_OFFSETOF(ObTracking, building_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "installation_id",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTracking, has_installation_id),
    PROTOBUF_C_OFFSETOF(ObTracking, installation_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_tracking__field_indices_by_name[] = {
  6,   /* field[6] = area_id */
  8,   /* field[8] = building_id */
  9,   /* field[9] = installation_id */
  4,   /* field[4] = reader_id */
  7,   /* field[7] = room_id */
  5,   /* field[5] = tx_strength */
  3,   /* field[3] = unit */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange ob_tracking__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor ob_tracking__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ObTracking",
  "ObTracking",
  "ObTracking",
  "",
  sizeof(ObTracking),
  10,
  ob_tracking__field_descriptors,
  ob_tracking__field_indices_by_name,
  1,  ob_tracking__number_ranges,
  (ProtobufCMessageInit) ob_tracking__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_proximity_tag_power__field_descriptors[2] =
{
  {
    "power",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObProximityTagPower, has_power),
    PROTOBUF_C_OFFSETOF(ObProximityTagPower, power),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObProximityTagPower, has_count),
    PROTOBUF_C_OFFSETOF(ObProximityTagPower, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_proximity_tag_power__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = power */
};
static const ProtobufCIntRange ob_proximity_tag_power__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ob_proximity_tag_power__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ObProximityTagPower",
  "ObProximityTagPower",
  "ObProximityTagPower",
  "",
  sizeof(ObProximityTagPower),
  2,
  ob_proximity_tag_power__field_descriptors,
  ob_proximity_tag_power__field_indices_by_name,
  1,  ob_proximity_tag_power__number_ranges,
  (ProtobufCMessageInit) ob_proximity_tag_power__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_proximity_tag__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ObProximityTag, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(ObProximityTag, n_power),
    PROTOBUF_C_OFFSETOF(ObProximityTag, power),
    &ob_proximity_tag_power__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_proximity_tag__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = power */
};
static const ProtobufCIntRange ob_proximity_tag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ob_proximity_tag__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ObProximityTag",
  "ObProximityTag",
  "ObProximityTag",
  "",
  sizeof(ObProximityTag),
  2,
  ob_proximity_tag__field_descriptors,
  ob_proximity_tag__field_indices_by_name,
  1,  ob_proximity_tag__number_ranges,
  (ProtobufCMessageInit) ob_proximity_tag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_proximity_log__field_descriptors[3] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ObProximityLog, time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ObProximityLog, duration),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(ObProximityLog, n_tag),
    PROTOBUF_C_OFFSETOF(ObProximityLog, tag),
    &ob_proximity_tag__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_proximity_log__field_indices_by_name[] = {
  1,   /* field[1] = duration */
  2,   /* field[2] = tag */
  0,   /* field[0] = time */
};
static const ProtobufCIntRange ob_proximity_log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ob_proximity_log__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ObProximityLog",
  "ObProximityLog",
  "ObProximityLog",
  "",
  sizeof(ObProximityLog),
  3,
  ob_proximity_log__field_descriptors,
  ob_proximity_log__field_indices_by_name,
  1,  ob_proximity_log__number_ranges,
  (ProtobufCMessageInit) ob_proximity_log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_tag__field_descriptors[9] =
{
  {
    "tag_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, has_tag_id),
    PROTOBUF_C_OFFSETOF(ObTag, tag_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, has_tag_time),
    PROTOBUF_C_OFFSETOF(ObTag, tag_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag_power_cycles",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, has_tag_power_cycles),
    PROTOBUF_C_OFFSETOF(ObTag, tag_power_cycles),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag_strength",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, has_tag_strength),
    PROTOBUF_C_OFFSETOF(ObTag, tag_strength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forwarder_id",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, n_forwarder_id),
    PROTOBUF_C_OFFSETOF(ObTag, forwarder_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forwarder_storage_time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ObTag, has_forwarder_storage_time),
    PROTOBUF_C_OFFSETOF(ObTag, forwarder_storage_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_time",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ObTag, has_rx_time),
    PROTOBUF_C_OFFSETOF(ObTag, rx_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracking",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ObTag, tracking),
    &ob_tracking__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proximity",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(ObTag, n_proximity),
    PROTOBUF_C_OFFSETOF(ObTag, proximity),
    &ob_proximity_log__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_tag__field_indices_by_name[] = {
  4,   /* field[4] = forwarder_id */
  5,   /* field[5] = forwarder_storage_time */
  8,   /* field[8] = proximity */
  6,   /* field[6] = rx_time */
  0,   /* field[0] = tag_id */
  2,   /* field[2] = tag_power_cycles */
  3,   /* field[3] = tag_strength */
  1,   /* field[1] = tag_time */
  7,   /* field[7] = tracking */
};
static const ProtobufCIntRange ob_tag__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 7 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ob_tag__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ObTag",
  "ObTag",
  "ObTag",
  "",
  sizeof(ObTag),
  9,
  ob_tag__field_descriptors,
  ob_tag__field_indices_by_name,
  2,  ob_tag__number_ranges,
  (ProtobufCMessageInit) ob_tag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue ob_unit__enum_values_by_number[8] =
{
  { "OB_UNIT_NONE", "OB_UNIT__OB_UNIT_NONE", 0 },
  { "OB_UNIT_PIXEL", "OB_UNIT__OB_UNIT_PIXEL", 1 },
  { "OB_UNIT_MILLIMETER", "OB_UNIT__OB_UNIT_MILLIMETER", 2 },
  { "OB_UNIT_CENTIMETER", "OB_UNIT__OB_UNIT_CENTIMETER", 3 },
  { "OB_UNIT_METER", "OB_UNIT__OB_UNIT_METER", 4 },
  { "OB_UNIT_INCH", "OB_UNIT__OB_UNIT_INCH", 5 },
  { "OB_UNIT_FEET", "OB_UNIT__OB_UNIT_FEET", 6 },
  { "OB_UNIT_YARD", "OB_UNIT__OB_UNIT_YARD", 7 },
};
static const ProtobufCIntRange ob_unit__value_ranges[] = {
{0, 0},{0, 8}
};
const ProtobufCEnumValueIndex ob_unit__enum_values_by_name[8] =
{
  { "OB_UNIT_CENTIMETER", 3 },
  { "OB_UNIT_FEET", 6 },
  { "OB_UNIT_INCH", 5 },
  { "OB_UNIT_METER", 4 },
  { "OB_UNIT_MILLIMETER", 2 },
  { "OB_UNIT_NONE", 0 },
  { "OB_UNIT_PIXEL", 1 },
  { "OB_UNIT_YARD", 7 },
};
const ProtobufCEnumDescriptor ob_unit__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ObUnit",
  "ObUnit",
  "ObUnit",
  "",
  8,
  ob_unit__enum_values_by_number,
  8,
  ob_unit__enum_values_by_name,
  1,
  ob_unit__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
