/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_openbeacon_2eproto__INCLUDED
#define PROTOBUF_C_openbeacon_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _OpenBeacon__ObTracking OpenBeacon__ObTracking;
typedef struct _OpenBeacon__ObProximityTagPower OpenBeacon__ObProximityTagPower;
typedef struct _OpenBeacon__ObProximityTag OpenBeacon__ObProximityTag;
typedef struct _OpenBeacon__ObProximityLog OpenBeacon__ObProximityLog;
typedef struct _OpenBeacon__ObTag OpenBeacon__ObTag;


/* --- enums --- */

typedef enum _OpenBeacon__ObUnit {
  OPEN_BEACON__OB_UNIT__OB_UNIT_NONE = 0,
  OPEN_BEACON__OB_UNIT__OB_UNIT_PIXEL = 1,
  OPEN_BEACON__OB_UNIT__OB_UNIT_MILLIMETER = 2,
  OPEN_BEACON__OB_UNIT__OB_UNIT_CENTIMETER = 3,
  OPEN_BEACON__OB_UNIT__OB_UNIT_METER = 4,
  OPEN_BEACON__OB_UNIT__OB_UNIT_INCH = 5,
  OPEN_BEACON__OB_UNIT__OB_UNIT_FEET = 6,
  OPEN_BEACON__OB_UNIT__OB_UNIT_YARD = 7
} OpenBeacon__ObUnit;

/* --- messages --- */

struct  _OpenBeacon__ObTracking
{
  ProtobufCMessage base;
  protobuf_c_boolean has_x;
  int32_t x;
  protobuf_c_boolean has_y;
  int32_t y;
  protobuf_c_boolean has_z;
  int32_t z;
  protobuf_c_boolean has_unit;
  OpenBeacon__ObUnit unit;
  size_t n_reader_id;
  uint32_t *reader_id;
  protobuf_c_boolean has_tx_strength;
  uint32_t tx_strength;
  protobuf_c_boolean has_area_id;
  uint32_t area_id;
  protobuf_c_boolean has_room_id;
  uint32_t room_id;
  protobuf_c_boolean has_building_id;
  uint32_t building_id;
  protobuf_c_boolean has_installation_id;
  uint32_t installation_id;
};
#define OPEN_BEACON__OB_TRACKING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_beacon__ob_tracking__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,NULL, 0,0, 0,0, 0,0, 0,0, 0,0 }


struct  _OpenBeacon__ObProximityTagPower
{
  ProtobufCMessage base;
  protobuf_c_boolean has_power;
  uint32_t power;
  protobuf_c_boolean has_count;
  uint32_t count;
};
#define OPEN_BEACON__OB_PROXIMITY_TAG_POWER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_beacon__ob_proximity_tag_power__descriptor) \
    , 0,0, 0,0 }


struct  _OpenBeacon__ObProximityTag
{
  ProtobufCMessage base;
  uint32_t id;
  size_t n_power;
  OpenBeacon__ObProximityTagPower **power;
};
#define OPEN_BEACON__OB_PROXIMITY_TAG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_beacon__ob_proximity_tag__descriptor) \
    , 0, 0,NULL }


struct  _OpenBeacon__ObProximityLog
{
  ProtobufCMessage base;
  uint32_t time;
  uint32_t duration;
  size_t n_tag;
  OpenBeacon__ObProximityTag **tag;
};
#define OPEN_BEACON__OB_PROXIMITY_LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_beacon__ob_proximity_log__descriptor) \
    , 0, 0, 0,NULL }


struct  _OpenBeacon__ObTag
{
  ProtobufCMessage base;
  protobuf_c_boolean has_tag_id;
  uint32_t tag_id;
  protobuf_c_boolean has_tag_time;
  uint32_t tag_time;
  protobuf_c_boolean has_tag_power_cycles;
  uint32_t tag_power_cycles;
  protobuf_c_boolean has_tag_strength;
  uint32_t tag_strength;
  size_t n_forwarder_id;
  uint32_t *forwarder_id;
  protobuf_c_boolean has_forwarder_storage_time;
  uint32_t forwarder_storage_time;
  protobuf_c_boolean has_rx_time;
  uint64_t rx_time;
  OpenBeacon__ObTracking *tracking;
  size_t n_proximity;
  OpenBeacon__ObProximityLog **proximity;
};
#define OPEN_BEACON__OB_TAG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&open_beacon__ob_tag__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,NULL, 0,0, 0,0, NULL, 0,NULL }


/* OpenBeacon__ObTracking methods */
void   open_beacon__ob_tracking__init
                     (OpenBeacon__ObTracking         *message);
size_t open_beacon__ob_tracking__get_packed_size
                     (const OpenBeacon__ObTracking   *message);
size_t open_beacon__ob_tracking__pack
                     (const OpenBeacon__ObTracking   *message,
                      uint8_t             *out);
size_t open_beacon__ob_tracking__pack_to_buffer
                     (const OpenBeacon__ObTracking   *message,
                      ProtobufCBuffer     *buffer);
OpenBeacon__ObTracking *
       open_beacon__ob_tracking__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_beacon__ob_tracking__free_unpacked
                     (OpenBeacon__ObTracking *message,
                      ProtobufCAllocator *allocator);
/* OpenBeacon__ObProximityTagPower methods */
void   open_beacon__ob_proximity_tag_power__init
                     (OpenBeacon__ObProximityTagPower         *message);
size_t open_beacon__ob_proximity_tag_power__get_packed_size
                     (const OpenBeacon__ObProximityTagPower   *message);
size_t open_beacon__ob_proximity_tag_power__pack
                     (const OpenBeacon__ObProximityTagPower   *message,
                      uint8_t             *out);
size_t open_beacon__ob_proximity_tag_power__pack_to_buffer
                     (const OpenBeacon__ObProximityTagPower   *message,
                      ProtobufCBuffer     *buffer);
OpenBeacon__ObProximityTagPower *
       open_beacon__ob_proximity_tag_power__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_beacon__ob_proximity_tag_power__free_unpacked
                     (OpenBeacon__ObProximityTagPower *message,
                      ProtobufCAllocator *allocator);
/* OpenBeacon__ObProximityTag methods */
void   open_beacon__ob_proximity_tag__init
                     (OpenBeacon__ObProximityTag         *message);
size_t open_beacon__ob_proximity_tag__get_packed_size
                     (const OpenBeacon__ObProximityTag   *message);
size_t open_beacon__ob_proximity_tag__pack
                     (const OpenBeacon__ObProximityTag   *message,
                      uint8_t             *out);
size_t open_beacon__ob_proximity_tag__pack_to_buffer
                     (const OpenBeacon__ObProximityTag   *message,
                      ProtobufCBuffer     *buffer);
OpenBeacon__ObProximityTag *
       open_beacon__ob_proximity_tag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_beacon__ob_proximity_tag__free_unpacked
                     (OpenBeacon__ObProximityTag *message,
                      ProtobufCAllocator *allocator);
/* OpenBeacon__ObProximityLog methods */
void   open_beacon__ob_proximity_log__init
                     (OpenBeacon__ObProximityLog         *message);
size_t open_beacon__ob_proximity_log__get_packed_size
                     (const OpenBeacon__ObProximityLog   *message);
size_t open_beacon__ob_proximity_log__pack
                     (const OpenBeacon__ObProximityLog   *message,
                      uint8_t             *out);
size_t open_beacon__ob_proximity_log__pack_to_buffer
                     (const OpenBeacon__ObProximityLog   *message,
                      ProtobufCBuffer     *buffer);
OpenBeacon__ObProximityLog *
       open_beacon__ob_proximity_log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_beacon__ob_proximity_log__free_unpacked
                     (OpenBeacon__ObProximityLog *message,
                      ProtobufCAllocator *allocator);
/* OpenBeacon__ObTag methods */
void   open_beacon__ob_tag__init
                     (OpenBeacon__ObTag         *message);
size_t open_beacon__ob_tag__get_packed_size
                     (const OpenBeacon__ObTag   *message);
size_t open_beacon__ob_tag__pack
                     (const OpenBeacon__ObTag   *message,
                      uint8_t             *out);
size_t open_beacon__ob_tag__pack_to_buffer
                     (const OpenBeacon__ObTag   *message,
                      ProtobufCBuffer     *buffer);
OpenBeacon__ObTag *
       open_beacon__ob_tag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   open_beacon__ob_tag__free_unpacked
                     (OpenBeacon__ObTag *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OpenBeacon__ObTracking_Closure)
                 (const OpenBeacon__ObTracking *message,
                  void *closure_data);
typedef void (*OpenBeacon__ObProximityTagPower_Closure)
                 (const OpenBeacon__ObProximityTagPower *message,
                  void *closure_data);
typedef void (*OpenBeacon__ObProximityTag_Closure)
                 (const OpenBeacon__ObProximityTag *message,
                  void *closure_data);
typedef void (*OpenBeacon__ObProximityLog_Closure)
                 (const OpenBeacon__ObProximityLog *message,
                  void *closure_data);
typedef void (*OpenBeacon__ObTag_Closure)
                 (const OpenBeacon__ObTag *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    open_beacon__ob_unit__descriptor;
extern const ProtobufCMessageDescriptor open_beacon__ob_tracking__descriptor;
extern const ProtobufCMessageDescriptor open_beacon__ob_proximity_tag_power__descriptor;
extern const ProtobufCMessageDescriptor open_beacon__ob_proximity_tag__descriptor;
extern const ProtobufCMessageDescriptor open_beacon__ob_proximity_log__descriptor;
extern const ProtobufCMessageDescriptor open_beacon__ob_tag__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_openbeacon_2eproto__INCLUDED */
