// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openbeacon.proto

#ifndef PROTOBUF_openbeacon_2eproto__INCLUDED
#define PROTOBUF_openbeacon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_openbeacon_2eproto();
void protobuf_AssignDesc_openbeacon_2eproto();
void protobuf_ShutdownFile_openbeacon_2eproto();

class ObTracking;
class ObProximityTagPower;
class ObProximityTag;
class ObProximityLog;
class ObTag;

enum ObUnit {
  OB_UNIT_NONE = 0,
  OB_UNIT_PIXEL = 1,
  OB_UNIT_MILLIMETER = 2,
  OB_UNIT_CENTIMETER = 3,
  OB_UNIT_METER = 4,
  OB_UNIT_INCH = 5,
  OB_UNIT_FEET = 6,
  OB_UNIT_YARD = 7
};
bool ObUnit_IsValid(int value);
const ObUnit ObUnit_MIN = OB_UNIT_NONE;
const ObUnit ObUnit_MAX = OB_UNIT_YARD;
const int ObUnit_ARRAYSIZE = ObUnit_MAX + 1;

const ::google::protobuf::EnumDescriptor* ObUnit_descriptor();
inline const ::std::string& ObUnit_Name(ObUnit value) {
  return ::google::protobuf::internal::NameOfEnum(
    ObUnit_descriptor(), value);
}
inline bool ObUnit_Parse(
    const ::std::string& name, ObUnit* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObUnit>(
    ObUnit_descriptor(), name, value);
}
// ===================================================================

class ObTracking : public ::google::protobuf::Message {
 public:
  ObTracking();
  virtual ~ObTracking();
  
  ObTracking(const ObTracking& from);
  
  inline ObTracking& operator=(const ObTracking& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObTracking& default_instance();
  
  void Swap(ObTracking* other);
  
  // implements Message ----------------------------------------------
  
  ObTracking* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObTracking& from);
  void MergeFrom(const ObTracking& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional sint32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // optional sint32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // optional sint32 z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline ::google::protobuf::int32 z() const;
  inline void set_z(::google::protobuf::int32 value);
  
  // optional .ObUnit unit = 4;
  inline bool has_unit() const;
  inline void clear_unit();
  static const int kUnitFieldNumber = 4;
  inline ObUnit unit() const;
  inline void set_unit(ObUnit value);
  
  // repeated uint32 reader_id = 5;
  inline int reader_id_size() const;
  inline void clear_reader_id();
  static const int kReaderIdFieldNumber = 5;
  inline ::google::protobuf::uint32 reader_id(int index) const;
  inline void set_reader_id(int index, ::google::protobuf::uint32 value);
  inline void add_reader_id(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      reader_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_reader_id();
  
  // optional uint32 tx_strength = 6;
  inline bool has_tx_strength() const;
  inline void clear_tx_strength();
  static const int kTxStrengthFieldNumber = 6;
  inline ::google::protobuf::uint32 tx_strength() const;
  inline void set_tx_strength(::google::protobuf::uint32 value);
  
  // optional uint32 area_id = 7;
  inline bool has_area_id() const;
  inline void clear_area_id();
  static const int kAreaIdFieldNumber = 7;
  inline ::google::protobuf::uint32 area_id() const;
  inline void set_area_id(::google::protobuf::uint32 value);
  
  // optional uint32 room_id = 8;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 8;
  inline ::google::protobuf::uint32 room_id() const;
  inline void set_room_id(::google::protobuf::uint32 value);
  
  // optional uint32 building_id = 9;
  inline bool has_building_id() const;
  inline void clear_building_id();
  static const int kBuildingIdFieldNumber = 9;
  inline ::google::protobuf::uint32 building_id() const;
  inline void set_building_id(::google::protobuf::uint32 value);
  
  // optional uint32 installation_id = 10;
  inline bool has_installation_id() const;
  inline void clear_installation_id();
  static const int kInstallationIdFieldNumber = 10;
  inline ::google::protobuf::uint32 installation_id() const;
  inline void set_installation_id(::google::protobuf::uint32 value);
  
  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ObTracking)
  // @@protoc_insertion_point(class_scope:ObTracking)
 private:
  ::google::protobuf::internal::ExtensionSet _extensions_;
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 z_;
  int unit_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > reader_id_;
  ::google::protobuf::uint32 tx_strength_;
  ::google::protobuf::uint32 area_id_;
  ::google::protobuf::uint32 room_id_;
  ::google::protobuf::uint32 building_id_;
  ::google::protobuf::uint32 installation_id_;
  friend void  protobuf_AddDesc_openbeacon_2eproto();
  friend void protobuf_AssignDesc_openbeacon_2eproto();
  friend void protobuf_ShutdownFile_openbeacon_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ObTracking* default_instance_;
};
// -------------------------------------------------------------------

class ObProximityTagPower : public ::google::protobuf::Message {
 public:
  ObProximityTagPower();
  virtual ~ObProximityTagPower();
  
  ObProximityTagPower(const ObProximityTagPower& from);
  
  inline ObProximityTagPower& operator=(const ObProximityTagPower& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObProximityTagPower& default_instance();
  
  void Swap(ObProximityTagPower* other);
  
  // implements Message ----------------------------------------------
  
  ObProximityTagPower* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObProximityTagPower& from);
  void MergeFrom(const ObProximityTagPower& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 power = 1;
  inline bool has_power() const;
  inline void clear_power();
  static const int kPowerFieldNumber = 1;
  inline ::google::protobuf::uint32 power() const;
  inline void set_power(::google::protobuf::uint32 value);
  
  // optional uint32 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::uint32 count() const;
  inline void set_count(::google::protobuf::uint32 value);
  
  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ObProximityTagPower)
  // @@protoc_insertion_point(class_scope:ObProximityTagPower)
 private:
  ::google::protobuf::internal::ExtensionSet _extensions_;
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 power_;
  ::google::protobuf::uint32 count_;
  friend void  protobuf_AddDesc_openbeacon_2eproto();
  friend void protobuf_AssignDesc_openbeacon_2eproto();
  friend void protobuf_ShutdownFile_openbeacon_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ObProximityTagPower* default_instance_;
};
// -------------------------------------------------------------------

class ObProximityTag : public ::google::protobuf::Message {
 public:
  ObProximityTag();
  virtual ~ObProximityTag();
  
  ObProximityTag(const ObProximityTag& from);
  
  inline ObProximityTag& operator=(const ObProximityTag& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObProximityTag& default_instance();
  
  void Swap(ObProximityTag* other);
  
  // implements Message ----------------------------------------------
  
  ObProximityTag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObProximityTag& from);
  void MergeFrom(const ObProximityTag& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // repeated .ObProximityTagPower power = 2;
  inline int power_size() const;
  inline void clear_power();
  static const int kPowerFieldNumber = 2;
  inline const ::ObProximityTagPower& power(int index) const;
  inline ::ObProximityTagPower* mutable_power(int index);
  inline ::ObProximityTagPower* add_power();
  inline const ::google::protobuf::RepeatedPtrField< ::ObProximityTagPower >&
      power() const;
  inline ::google::protobuf::RepeatedPtrField< ::ObProximityTagPower >*
      mutable_power();
  
  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ObProximityTag)
  // @@protoc_insertion_point(class_scope:ObProximityTag)
 private:
  ::google::protobuf::internal::ExtensionSet _extensions_;
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 id_;
  ::google::protobuf::RepeatedPtrField< ::ObProximityTagPower > power_;
  friend void  protobuf_AddDesc_openbeacon_2eproto();
  friend void protobuf_AssignDesc_openbeacon_2eproto();
  friend void protobuf_ShutdownFile_openbeacon_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ObProximityTag* default_instance_;
};
// -------------------------------------------------------------------

class ObProximityLog : public ::google::protobuf::Message {
 public:
  ObProximityLog();
  virtual ~ObProximityLog();
  
  ObProximityLog(const ObProximityLog& from);
  
  inline ObProximityLog& operator=(const ObProximityLog& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObProximityLog& default_instance();
  
  void Swap(ObProximityLog* other);
  
  // implements Message ----------------------------------------------
  
  ObProximityLog* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObProximityLog& from);
  void MergeFrom(const ObProximityLog& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);
  
  // required uint32 duration = 2;
  inline bool has_duration() const;
  inline void clear_duration();
  static const int kDurationFieldNumber = 2;
  inline ::google::protobuf::uint32 duration() const;
  inline void set_duration(::google::protobuf::uint32 value);
  
  // repeated .ObProximityTag tag = 3;
  inline int tag_size() const;
  inline void clear_tag();
  static const int kTagFieldNumber = 3;
  inline const ::ObProximityTag& tag(int index) const;
  inline ::ObProximityTag* mutable_tag(int index);
  inline ::ObProximityTag* add_tag();
  inline const ::google::protobuf::RepeatedPtrField< ::ObProximityTag >&
      tag() const;
  inline ::google::protobuf::RepeatedPtrField< ::ObProximityTag >*
      mutable_tag();
  
  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ObProximityLog)
  // @@protoc_insertion_point(class_scope:ObProximityLog)
 private:
  ::google::protobuf::internal::ExtensionSet _extensions_;
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 time_;
  ::google::protobuf::uint32 duration_;
  ::google::protobuf::RepeatedPtrField< ::ObProximityTag > tag_;
  friend void  protobuf_AddDesc_openbeacon_2eproto();
  friend void protobuf_AssignDesc_openbeacon_2eproto();
  friend void protobuf_ShutdownFile_openbeacon_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ObProximityLog* default_instance_;
};
// -------------------------------------------------------------------

class ObTag : public ::google::protobuf::Message {
 public:
  ObTag();
  virtual ~ObTag();
  
  ObTag(const ObTag& from);
  
  inline ObTag& operator=(const ObTag& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObTag& default_instance();
  
  void Swap(ObTag* other);
  
  // implements Message ----------------------------------------------
  
  ObTag* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObTag& from);
  void MergeFrom(const ObTag& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 tag_id = 1;
  inline bool has_tag_id() const;
  inline void clear_tag_id();
  static const int kTagIdFieldNumber = 1;
  inline ::google::protobuf::uint32 tag_id() const;
  inline void set_tag_id(::google::protobuf::uint32 value);
  
  // optional uint32 tag_time = 2;
  inline bool has_tag_time() const;
  inline void clear_tag_time();
  static const int kTagTimeFieldNumber = 2;
  inline ::google::protobuf::uint32 tag_time() const;
  inline void set_tag_time(::google::protobuf::uint32 value);
  
  // optional uint32 tag_power_cycles = 3;
  inline bool has_tag_power_cycles() const;
  inline void clear_tag_power_cycles();
  static const int kTagPowerCyclesFieldNumber = 3;
  inline ::google::protobuf::uint32 tag_power_cycles() const;
  inline void set_tag_power_cycles(::google::protobuf::uint32 value);
  
  // optional uint32 tag_strength = 4;
  inline bool has_tag_strength() const;
  inline void clear_tag_strength();
  static const int kTagStrengthFieldNumber = 4;
  inline ::google::protobuf::uint32 tag_strength() const;
  inline void set_tag_strength(::google::protobuf::uint32 value);
  
  // repeated uint32 forwarder_id = 5;
  inline int forwarder_id_size() const;
  inline void clear_forwarder_id();
  static const int kForwarderIdFieldNumber = 5;
  inline ::google::protobuf::uint32 forwarder_id(int index) const;
  inline void set_forwarder_id(int index, ::google::protobuf::uint32 value);
  inline void add_forwarder_id(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      forwarder_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_forwarder_id();
  
  // optional uint32 forwarder_storage_time = 6;
  inline bool has_forwarder_storage_time() const;
  inline void clear_forwarder_storage_time();
  static const int kForwarderStorageTimeFieldNumber = 6;
  inline ::google::protobuf::uint32 forwarder_storage_time() const;
  inline void set_forwarder_storage_time(::google::protobuf::uint32 value);
  
  // optional uint64 rx_time = 7;
  inline bool has_rx_time() const;
  inline void clear_rx_time();
  static const int kRxTimeFieldNumber = 7;
  inline ::google::protobuf::uint64 rx_time() const;
  inline void set_rx_time(::google::protobuf::uint64 value);
  
  // optional .ObTracking tracking = 14;
  inline bool has_tracking() const;
  inline void clear_tracking();
  static const int kTrackingFieldNumber = 14;
  inline const ::ObTracking& tracking() const;
  inline ::ObTracking* mutable_tracking();
  
  // repeated .ObProximityLog proximity = 15;
  inline int proximity_size() const;
  inline void clear_proximity();
  static const int kProximityFieldNumber = 15;
  inline const ::ObProximityLog& proximity(int index) const;
  inline ::ObProximityLog* mutable_proximity(int index);
  inline ::ObProximityLog* add_proximity();
  inline const ::google::protobuf::RepeatedPtrField< ::ObProximityLog >&
      proximity() const;
  inline ::google::protobuf::RepeatedPtrField< ::ObProximityLog >*
      mutable_proximity();
  
  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ObTag)
  // @@protoc_insertion_point(class_scope:ObTag)
 private:
  ::google::protobuf::internal::ExtensionSet _extensions_;
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 tag_id_;
  ::google::protobuf::uint32 tag_time_;
  ::google::protobuf::uint32 tag_power_cycles_;
  ::google::protobuf::uint32 tag_strength_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > forwarder_id_;
  ::google::protobuf::uint32 forwarder_storage_time_;
  ::google::protobuf::uint64 rx_time_;
  ::ObTracking* tracking_;
  ::google::protobuf::RepeatedPtrField< ::ObProximityLog > proximity_;
  friend void  protobuf_AddDesc_openbeacon_2eproto();
  friend void protobuf_AssignDesc_openbeacon_2eproto();
  friend void protobuf_ShutdownFile_openbeacon_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ObTag* default_instance_;
};
// ===================================================================


// ===================================================================

// ObTracking

// optional sint32 x = 1;
inline bool ObTracking::has_x() const {
  return _has_bit(0);
}
inline void ObTracking::clear_x() {
  x_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ObTracking::x() const {
  return x_;
}
inline void ObTracking::set_x(::google::protobuf::int32 value) {
  _set_bit(0);
  x_ = value;
}

// optional sint32 y = 2;
inline bool ObTracking::has_y() const {
  return _has_bit(1);
}
inline void ObTracking::clear_y() {
  y_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 ObTracking::y() const {
  return y_;
}
inline void ObTracking::set_y(::google::protobuf::int32 value) {
  _set_bit(1);
  y_ = value;
}

// optional sint32 z = 3;
inline bool ObTracking::has_z() const {
  return _has_bit(2);
}
inline void ObTracking::clear_z() {
  z_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 ObTracking::z() const {
  return z_;
}
inline void ObTracking::set_z(::google::protobuf::int32 value) {
  _set_bit(2);
  z_ = value;
}

// optional .ObUnit unit = 4;
inline bool ObTracking::has_unit() const {
  return _has_bit(3);
}
inline void ObTracking::clear_unit() {
  unit_ = 0;
  _clear_bit(3);
}
inline ObUnit ObTracking::unit() const {
  return static_cast< ObUnit >(unit_);
}
inline void ObTracking::set_unit(ObUnit value) {
  GOOGLE_DCHECK(ObUnit_IsValid(value));
  _set_bit(3);
  unit_ = value;
}

// repeated uint32 reader_id = 5;
inline int ObTracking::reader_id_size() const {
  return reader_id_.size();
}
inline void ObTracking::clear_reader_id() {
  reader_id_.Clear();
}
inline ::google::protobuf::uint32 ObTracking::reader_id(int index) const {
  return reader_id_.Get(index);
}
inline void ObTracking::set_reader_id(int index, ::google::protobuf::uint32 value) {
  reader_id_.Set(index, value);
}
inline void ObTracking::add_reader_id(::google::protobuf::uint32 value) {
  reader_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ObTracking::reader_id() const {
  return reader_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ObTracking::mutable_reader_id() {
  return &reader_id_;
}

// optional uint32 tx_strength = 6;
inline bool ObTracking::has_tx_strength() const {
  return _has_bit(5);
}
inline void ObTracking::clear_tx_strength() {
  tx_strength_ = 0u;
  _clear_bit(5);
}
inline ::google::protobuf::uint32 ObTracking::tx_strength() const {
  return tx_strength_;
}
inline void ObTracking::set_tx_strength(::google::protobuf::uint32 value) {
  _set_bit(5);
  tx_strength_ = value;
}

// optional uint32 area_id = 7;
inline bool ObTracking::has_area_id() const {
  return _has_bit(6);
}
inline void ObTracking::clear_area_id() {
  area_id_ = 0u;
  _clear_bit(6);
}
inline ::google::protobuf::uint32 ObTracking::area_id() const {
  return area_id_;
}
inline void ObTracking::set_area_id(::google::protobuf::uint32 value) {
  _set_bit(6);
  area_id_ = value;
}

// optional uint32 room_id = 8;
inline bool ObTracking::has_room_id() const {
  return _has_bit(7);
}
inline void ObTracking::clear_room_id() {
  room_id_ = 0u;
  _clear_bit(7);
}
inline ::google::protobuf::uint32 ObTracking::room_id() const {
  return room_id_;
}
inline void ObTracking::set_room_id(::google::protobuf::uint32 value) {
  _set_bit(7);
  room_id_ = value;
}

// optional uint32 building_id = 9;
inline bool ObTracking::has_building_id() const {
  return _has_bit(8);
}
inline void ObTracking::clear_building_id() {
  building_id_ = 0u;
  _clear_bit(8);
}
inline ::google::protobuf::uint32 ObTracking::building_id() const {
  return building_id_;
}
inline void ObTracking::set_building_id(::google::protobuf::uint32 value) {
  _set_bit(8);
  building_id_ = value;
}

// optional uint32 installation_id = 10;
inline bool ObTracking::has_installation_id() const {
  return _has_bit(9);
}
inline void ObTracking::clear_installation_id() {
  installation_id_ = 0u;
  _clear_bit(9);
}
inline ::google::protobuf::uint32 ObTracking::installation_id() const {
  return installation_id_;
}
inline void ObTracking::set_installation_id(::google::protobuf::uint32 value) {
  _set_bit(9);
  installation_id_ = value;
}

// -------------------------------------------------------------------

// ObProximityTagPower

// optional uint32 power = 1;
inline bool ObProximityTagPower::has_power() const {
  return _has_bit(0);
}
inline void ObProximityTagPower::clear_power() {
  power_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 ObProximityTagPower::power() const {
  return power_;
}
inline void ObProximityTagPower::set_power(::google::protobuf::uint32 value) {
  _set_bit(0);
  power_ = value;
}

// optional uint32 count = 2;
inline bool ObProximityTagPower::has_count() const {
  return _has_bit(1);
}
inline void ObProximityTagPower::clear_count() {
  count_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 ObProximityTagPower::count() const {
  return count_;
}
inline void ObProximityTagPower::set_count(::google::protobuf::uint32 value) {
  _set_bit(1);
  count_ = value;
}

// -------------------------------------------------------------------

// ObProximityTag

// required uint32 id = 1;
inline bool ObProximityTag::has_id() const {
  return _has_bit(0);
}
inline void ObProximityTag::clear_id() {
  id_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 ObProximityTag::id() const {
  return id_;
}
inline void ObProximityTag::set_id(::google::protobuf::uint32 value) {
  _set_bit(0);
  id_ = value;
}

// repeated .ObProximityTagPower power = 2;
inline int ObProximityTag::power_size() const {
  return power_.size();
}
inline void ObProximityTag::clear_power() {
  power_.Clear();
}
inline const ::ObProximityTagPower& ObProximityTag::power(int index) const {
  return power_.Get(index);
}
inline ::ObProximityTagPower* ObProximityTag::mutable_power(int index) {
  return power_.Mutable(index);
}
inline ::ObProximityTagPower* ObProximityTag::add_power() {
  return power_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ObProximityTagPower >&
ObProximityTag::power() const {
  return power_;
}
inline ::google::protobuf::RepeatedPtrField< ::ObProximityTagPower >*
ObProximityTag::mutable_power() {
  return &power_;
}

// -------------------------------------------------------------------

// ObProximityLog

// required uint32 time = 1;
inline bool ObProximityLog::has_time() const {
  return _has_bit(0);
}
inline void ObProximityLog::clear_time() {
  time_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 ObProximityLog::time() const {
  return time_;
}
inline void ObProximityLog::set_time(::google::protobuf::uint32 value) {
  _set_bit(0);
  time_ = value;
}

// required uint32 duration = 2;
inline bool ObProximityLog::has_duration() const {
  return _has_bit(1);
}
inline void ObProximityLog::clear_duration() {
  duration_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 ObProximityLog::duration() const {
  return duration_;
}
inline void ObProximityLog::set_duration(::google::protobuf::uint32 value) {
  _set_bit(1);
  duration_ = value;
}

// repeated .ObProximityTag tag = 3;
inline int ObProximityLog::tag_size() const {
  return tag_.size();
}
inline void ObProximityLog::clear_tag() {
  tag_.Clear();
}
inline const ::ObProximityTag& ObProximityLog::tag(int index) const {
  return tag_.Get(index);
}
inline ::ObProximityTag* ObProximityLog::mutable_tag(int index) {
  return tag_.Mutable(index);
}
inline ::ObProximityTag* ObProximityLog::add_tag() {
  return tag_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ObProximityTag >&
ObProximityLog::tag() const {
  return tag_;
}
inline ::google::protobuf::RepeatedPtrField< ::ObProximityTag >*
ObProximityLog::mutable_tag() {
  return &tag_;
}

// -------------------------------------------------------------------

// ObTag

// optional uint32 tag_id = 1;
inline bool ObTag::has_tag_id() const {
  return _has_bit(0);
}
inline void ObTag::clear_tag_id() {
  tag_id_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 ObTag::tag_id() const {
  return tag_id_;
}
inline void ObTag::set_tag_id(::google::protobuf::uint32 value) {
  _set_bit(0);
  tag_id_ = value;
}

// optional uint32 tag_time = 2;
inline bool ObTag::has_tag_time() const {
  return _has_bit(1);
}
inline void ObTag::clear_tag_time() {
  tag_time_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 ObTag::tag_time() const {
  return tag_time_;
}
inline void ObTag::set_tag_time(::google::protobuf::uint32 value) {
  _set_bit(1);
  tag_time_ = value;
}

// optional uint32 tag_power_cycles = 3;
inline bool ObTag::has_tag_power_cycles() const {
  return _has_bit(2);
}
inline void ObTag::clear_tag_power_cycles() {
  tag_power_cycles_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32 ObTag::tag_power_cycles() const {
  return tag_power_cycles_;
}
inline void ObTag::set_tag_power_cycles(::google::protobuf::uint32 value) {
  _set_bit(2);
  tag_power_cycles_ = value;
}

// optional uint32 tag_strength = 4;
inline bool ObTag::has_tag_strength() const {
  return _has_bit(3);
}
inline void ObTag::clear_tag_strength() {
  tag_strength_ = 0u;
  _clear_bit(3);
}
inline ::google::protobuf::uint32 ObTag::tag_strength() const {
  return tag_strength_;
}
inline void ObTag::set_tag_strength(::google::protobuf::uint32 value) {
  _set_bit(3);
  tag_strength_ = value;
}

// repeated uint32 forwarder_id = 5;
inline int ObTag::forwarder_id_size() const {
  return forwarder_id_.size();
}
inline void ObTag::clear_forwarder_id() {
  forwarder_id_.Clear();
}
inline ::google::protobuf::uint32 ObTag::forwarder_id(int index) const {
  return forwarder_id_.Get(index);
}
inline void ObTag::set_forwarder_id(int index, ::google::protobuf::uint32 value) {
  forwarder_id_.Set(index, value);
}
inline void ObTag::add_forwarder_id(::google::protobuf::uint32 value) {
  forwarder_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ObTag::forwarder_id() const {
  return forwarder_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ObTag::mutable_forwarder_id() {
  return &forwarder_id_;
}

// optional uint32 forwarder_storage_time = 6;
inline bool ObTag::has_forwarder_storage_time() const {
  return _has_bit(5);
}
inline void ObTag::clear_forwarder_storage_time() {
  forwarder_storage_time_ = 0u;
  _clear_bit(5);
}
inline ::google::protobuf::uint32 ObTag::forwarder_storage_time() const {
  return forwarder_storage_time_;
}
inline void ObTag::set_forwarder_storage_time(::google::protobuf::uint32 value) {
  _set_bit(5);
  forwarder_storage_time_ = value;
}

// optional uint64 rx_time = 7;
inline bool ObTag::has_rx_time() const {
  return _has_bit(6);
}
inline void ObTag::clear_rx_time() {
  rx_time_ = GOOGLE_ULONGLONG(0);
  _clear_bit(6);
}
inline ::google::protobuf::uint64 ObTag::rx_time() const {
  return rx_time_;
}
inline void ObTag::set_rx_time(::google::protobuf::uint64 value) {
  _set_bit(6);
  rx_time_ = value;
}

// optional .ObTracking tracking = 14;
inline bool ObTag::has_tracking() const {
  return _has_bit(7);
}
inline void ObTag::clear_tracking() {
  if (tracking_ != NULL) tracking_->::ObTracking::Clear();
  _clear_bit(7);
}
inline const ::ObTracking& ObTag::tracking() const {
  return tracking_ != NULL ? *tracking_ : *default_instance_->tracking_;
}
inline ::ObTracking* ObTag::mutable_tracking() {
  _set_bit(7);
  if (tracking_ == NULL) tracking_ = new ::ObTracking;
  return tracking_;
}

// repeated .ObProximityLog proximity = 15;
inline int ObTag::proximity_size() const {
  return proximity_.size();
}
inline void ObTag::clear_proximity() {
  proximity_.Clear();
}
inline const ::ObProximityLog& ObTag::proximity(int index) const {
  return proximity_.Get(index);
}
inline ::ObProximityLog* ObTag::mutable_proximity(int index) {
  return proximity_.Mutable(index);
}
inline ::ObProximityLog* ObTag::add_proximity() {
  return proximity_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ObProximityLog >&
ObTag::proximity() const {
  return proximity_;
}
inline ::google::protobuf::RepeatedPtrField< ::ObProximityLog >*
ObTag::mutable_proximity() {
  return &proximity_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ObUnit>() {
  return ObUnit_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openbeacon_2eproto__INCLUDED
