#!/bin/bash
#
# Used to generate a list of tag_id,password combinations (CSV) to be printed on a sticker
#

OUTPUT=sequence.txt

echo 'tag_id,password'>$OUTPUT
for i in {100..999}
do
    echo "$i,"` hexdump -v -n3 -e '1/1 "%02X"' /dev/urandom` >>$OUTPUT
done
